server:
  port: 8081

spring:
  datasource:
    name: todolist
    url: jdbc:mysql://127.0.0.1:3306/todolist?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: ysw12138
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.yangshiwei.todolist.model
  configuration:
    map-underscore-to-camel-case: true
